### ISSUE TITLE
Created image is always broken/white

### ISSUE THREAD

**Issue by xe4me** [willdady/emosaic#2]
Hi 
Thanks for your great work in advance.
Been trying to run it and there's no error, but the output image is always white/broken/can't be opened.
This is my source image

![a](https://user-images.githubusercontent.com/7995651/62819014-b5ba1000-bb92-11e9-96f9-afac4e91d661.png)

And these are my tiles : 

![b](https://user-images.githubusercontent.com/7995651/62819017-c1a5d200-bb92-11e9-85de-d0b9c5c9a583.png)
![c](https://user-images.githubusercontent.com/7995651/62819018-c23e6880-bb92-11e9-85ca-dc7b4b1dfe33.png)

**Comment by willdady** [comment]
Hi @xe4me. Thanks for giving it a go!

Assuming you are using the exact images you've included here and are not using the tile size option (`-o`) your resulting output fille will have dimensions of **61440x34560**! Your OS most-likely can't open/render the file as it's simply too huge. Your source image has dimensions of 3840x2160 which is way too large! Remember each **pixel** in the source image is a tile in the output image. 

If I resize your source image using [ImageMagick](https://imagemagick.org/) so it has a width of 70 pixels...

```
convert source.png -resize 70 source2.png
```

...and run it through emosaic you will get this:

![](https://i.imgur.com/yIKE36m.png)

Hope that make sense!

**Comment by xe4me** [comment]
Wow, I wasn't expecting you to be so quick on the answer. Thank you very very much.
Perhaps we/I could add some error/warnings about this inside the library itself, it would help a lot.
Much appreciated.

**Comment by willdady** [comment]
No worries. Glad to help. 🤓

Yes I was thinking the same. Inputing a file which is too-big or providing an empty directory should throw a useful error. Was also thinking of adding `-v, --verbose` option which prints out the step it's currently on.

Fun fact. That 61440x34560 image can be shrunken down by 25% and it will open (though the mosaic effect kinda gets lost).

```
convert output.png -resize 25% output2.png
```

Kinda cool Rust doesn't balk at creating such a large image 😃
